'use strict';

const STORAGE_KEY='roll_model_golf_active_round_v1';
const LEGACY_KEYS=['you_get_what_you_get_active_round_v1','rule12_challenge_round_v1'];
const CLUBS=['Driver','3-Wood','5-Wood','H1 / 2-Iron','3-Iron','4-Iron','5-Iron','6-Iron','7-Iron','8-Iron','9-Iron','PW','GW','SW','LW'];
const DRIVER_SUBSTITUTES=['3-Wood','5-Wood','H1 / 2-Iron','3-Iron','4-Iron','5-Iron','6-Iron','7-Iron','8-Iron','9-Iron'];
const RARITIES=['Common','Rare','Epic','Legendary'];
const RARITY_WEIGHTS={Common:50,Rare:30,Epic:15,Legendary:5};
const RARITY_STYLES={Common:'pending-common',Rare:'pending-rare',Epic:'pending-epic',Legendary:'pending-legendary'};
const DISTANCE_RULES={Common:{halfWindowRate:.25,reward:.10},Rare:{halfWindowRate:.15,reward:.25},Epic:{halfWindowRate:.10,reward:.50},Legendary:{halfWindowRate:.05,reward:1.00}};
const PUTTING_RULES={Common:{maximumPuttsPer18:40,maximumAveragePuttsPerHole:40/18,fullBonus:1},Rare:{maximumPuttsPer18:35,maximumAveragePuttsPerHole:35/18,fullBonus:2},Epic:{maximumPuttsPer18:32,maximumAveragePuttsPerHole:32/18,fullBonus:3},Legendary:{maximumPuttsPer18:29,maximumAveragePuttsPerHole:29/18,fullBonus:4}};
const CHIP_RULES={Common:{measurementBasis:'flagstick',multiplier:1,target:'within one full flagstick height of the cup',reward:.10},Rare:{measurementBasis:'flagstick',multiplier:.5,target:'within half a flagstick height of the cup',reward:.25},Epic:{measurementBasis:'playerFoot',multiplier:3,target:'within three of your actual foot lengths of the cup',reward:.50},Legendary:{measurementBasis:'playerFoot',multiplier:1,target:'within one of your actual foot lengths of the cup',reward:1.00}};
const SHORT_GAME_PROFILES=[{club:'5-Iron',ruleNumber:5,minLoft:24,maxLoft:29,representativeLoft:26.5},{club:'6-Iron',ruleNumber:6,minLoft:27,maxLoft:32,representativeLoft:29.5},{club:'7-Iron',ruleNumber:7,minLoft:29,maxLoft:35,representativeLoft:32},{club:'8-Iron',ruleNumber:8,minLoft:33,maxLoft:39,representativeLoft:36},{club:'9-Iron',ruleNumber:9,minLoft:37,maxLoft:43,representativeLoft:40},{club:'PW',ruleNumber:10,minLoft:43,maxLoft:48,representativeLoft:45.5},{club:'GW',ruleNumber:11,minLoft:48,maxLoft:52,representativeLoft:50},{club:'SW',ruleNumber:12,minLoft:54,maxLoft:58,representativeLoft:56},{club:'LW',ruleNumber:13,minLoft:58,maxLoft:64,representativeLoft:61}];
const SHORT_GAME_SPEEDS={veryfast:{label:'Very Fast — Rule of 14',base:14},fast:{label:'Fast — Rule of 13',base:13},normal:{label:'Normal — Rule of 12',base:12},slow:{label:'Slow — Rule of 11',base:11},veryslow:{label:'Very Slow — Rule of 10',base:10}};
const STROKE_CREDITS_PER_STROKE=100;
const state={profiles:[],pendingRole:null,pendingOptions:[],active:null,currentShot:null,currentPutting:null,currentAroundGreen:null,currentChipRecommendation:null,progressVisible:false,revealTimeouts:[]};
const $=(id)=>document.getElementById(id);
const els={randomizeBtn:$('randomizeBtn'),resumeBtn:$('resumeBtn'),resetBtn:$('resetBtn'),printBtn:$('printBtn'),liveStatus:$('liveStatus'),pendingSection:$('pendingSection'),pendingMeta:$('pendingMeta'),activeSection:$('activeSection'),activeMeta:$('activeMeta'),activeCard:$('activeCard'),playSection:$('playSection'),currentHoleOut:$('currentHoleOut'),puttingBtn:$('puttingBtn'),distanceGrid:$('distanceGrid'),playOut:$('playOut'),shotConfirmOut:$('shotConfirmOut'),playResetBtn:$('playResetBtn'),progressToggleWrap:$('progressToggleWrap'),roundScore:$('roundScore'),teeYardage:$('teeYardage'),printCardsSection:$('printCardsSection'),printGrid:$('printGrid'),zoomOverlay:$('zoomOverlay'),zoomImage:$('zoomImage'),zoomCloseBtn:$('zoomCloseBtn')};
function secureIndex(max){if(max<=0)return 0;if(window.crypto?.getRandomValues){const values=new Uint32Array(1);const limit=Math.floor(0x100000000/max)*max;let value;do{window.crypto.getRandomValues(values);value=values[0]}while(value>=limit);return value%max}return Math.floor(Math.random()*max)}
function format(value,decimals=2){return Number(value).toFixed(decimals)}
function formatDistance(value){return Number.isInteger(value)?String(value):Number(value).toFixed(1)}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function saveRound(){if(state.active)localStorage.setItem(STORAGE_KEY,JSON.stringify(state.active));else localStorage.removeItem(STORAGE_KEY)}
function profileById(id){return state.profiles.find((p)=>p.id===id)||null}
function findProfile(coinResult,dieRoll,rarity){return state.profiles.find((p)=>p.coinResult===coinResult&&p.dieRoll===dieRoll&&p.rarity===rarity)||null}
function activeProfile(){if(!state.active)return null;const source=profileById(state.active.profileId);if(!source)return null;return{...source,clubs:{...(state.active.clubs||source.clubs)},teeYardage:state.active.teeYardage??source.teeYardage,distanceModelVersion:state.active.distanceModelVersion||source.distanceModelVersion}}
function focusPlay(){if(!els.playSection.classList.contains('hidden')){els.playSection.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});els.playSection.focus({preventScroll:true})}}
function clearTimers(){state.revealTimeouts.forEach(clearTimeout);state.revealTimeouts=[]}
function updateInstructionVisibility(){const special=Boolean(state.currentPutting||state.currentAroundGreen||state.currentChipRecommendation);document.querySelectorAll('[data-round-instruction="true"]').forEach((node)=>node.classList.toggle('hidden',special))}
function validateProfiles(data){if(data?.game!=='Roll Play Golf'||!Array.isArray(data.profiles)||data.profiles.length!==48)throw new Error('Expected the 48-profile Roll Play Golf manifest.');const combos=new Set();for(const profile of data.profiles){const combo=`${profile.coinResult}|${profile.dieRoll}|${profile.rarity}`;if(combos.has(combo))throw new Error(`Duplicate profile combination: ${combo}`);combos.add(combo);for(let i=0;i<CLUBS.length;i+=1){const value=profile.clubs?.[CLUBS[i]];if(!Number.isInteger(value)||value<=0)throw new Error(`${profile.id}: invalid ${CLUBS[i]}`);if(i>0&&profile.clubs[CLUBS[i-1]]<=value)throw new Error(`${profile.id}: non-descending club ladder`)}}}
function loadProfiles(){const data=window.ROLL_PLAY_RESULTS;validateProfiles(data);state.profiles=data.profiles}
function migrateAndLoadRound(){let raw=localStorage.getItem(STORAGE_KEY);if(!raw){for(const key of LEGACY_KEYS){const candidate=localStorage.getItem(key);if(candidate){raw=candidate;break}}}if(raw){try{state.active=JSON.parse(raw)}catch{state.active=null}}if(!state.active)return;const profile=profileById(state.active.profileId||state.active.profile?.id);if(!profile||state.active.locked===false){state.active=null;saveRound();return}state.active.profileId=profile.id;state.active.gender=state.active.gender||profile.gender;state.active.ageGroup=state.active.ageGroup||profile.ageGroup;state.active.rarity=state.active.rarity||profile.rarity;state.active.archetypeName=state.active.archetypeName||profile.archetypeName;state.active.performanceLabel=state.active.performanceLabel||profile.performanceLabel;state.active.clubs={...(state.active.clubs||profile.clubs)};state.active.teeYardage=state.active.teeYardage??profile.teeYardage;state.active.distanceModelVersion=state.active.distanceModelVersion||profile.distanceModelVersion;state.active.startingHoleNumber=normalizeHole(state.active.startingHoleNumber||1);state.active.currentHoleNumber=normalizeHole(state.active.currentHoleNumber||1);state.active.startingHoleConfirmed=Boolean(state.active.startingHoleConfirmed||(state.active.shotResults?.length||state.active.chipResults?.length||state.active.puttingResults?.length));state.active.penaltyStrokesByHole=state.active.penaltyStrokesByHole&&typeof state.active.penaltyStrokesByHole==='object'?state.active.penaltyStrokesByHole:{};state.active.shotResults=Array.isArray(state.active.shotResults)?state.active.shotResults:[];state.active.chipResults=Array.isArray(state.active.chipResults)?state.active.chipResults:[];state.active.puttingResults=Array.isArray(state.active.puttingResults)?state.active.puttingResults:[];state.active.locked=true;saveRound()}
function rollWeightedRarityFrom(available){const total=available.reduce((s,r)=>s+RARITY_WEIGHTS[r],0);let roll=secureIndex(total)+1;for(const rarity of available){roll-=RARITY_WEIGHTS[rarity];if(roll<=0)return rarity}return available.at(-1)}
function rollCharacterRole(){return{coinResult:secureIndex(2)===0?'Heads':'Tails',dieRoll:secureIndex(6)+1}}
function buildPendingChoices(){const role=rollCharacterRole();state.pendingRole=role;const available=[...RARITIES];const options=[];while(options.length<3&&available.length){const rarity=rollWeightedRarityFrom(available);available.splice(available.indexOf(rarity),1);const profile=findProfile(role.coinResult,role.dieRoll,rarity);if(profile)options.push(profile)}return options}
function chipQuestText(rarity){return CHIP_RULES[rarity].target.replace(/^within /,'Within ')}
function setPendingOptions(profiles){state.pendingOptions=Array.isArray(profiles)?profiles:[];if(!state.pendingOptions.length){els.pendingSection.classList.add('hidden');els.pendingMeta.innerHTML='';return}const role=state.pendingOptions[0];const cards=state.pendingOptions.map((profile,index)=>{const rule=DISTANCE_RULES[profile.rarity];const putting=PUTTING_RULES[profile.rarity];return`<article class="pending-choice ${RARITY_STYLES[profile.rarity]}"><p class="pending-choice-title">${escapeHtml(profile.performanceLabel)}</p><div class="pending-choice-rarity">${profile.rarity.toUpperCase()}</div><div class="pending-choice-stat"><span>Driver</span><strong>${profile.clubs.Driver} yd</strong></div><div class="pending-choice-stat"><span>7-Iron</span><strong>${profile.clubs['7-Iron']} yd</strong></div><div class="pending-choice-stat"><span>PW</span><strong>${profile.clubs.PW} yd</strong></div><div class="pending-choice-stat"><span>Distance Quest</span><strong>±${Math.round(rule.halfWindowRate*100)}%</strong></div><div class="pending-choice-stat"><span>Reward</span><strong>${format(rule.reward)} stroke${rule.reward===1?'':'s'}</strong></div><div class="pending-choice-stat"><span>Putting Quest</span><strong>${format(putting.maximumAveragePuttsPerHole)} / hole</strong></div><p class="muted">Short-Game Quest: ${escapeHtml(chipQuestText(profile.rarity))}</p><button type="button" data-pending-index="${index}">Role-play ${profile.rarity}</button></article>`}).join('');els.pendingSection.classList.remove('hidden');els.pendingMeta.innerHTML=`<div class="role-reveal"><div class="score-label">YOUR GOLFER ROLE</div><div class="role-title">${escapeHtml(role.archetypeName)}</div><div class="role-meta">${role.gender} • ${escapeHtml(role.ageGroup)}</div><p class="muted">Choose the rarity version of this golfer you will role-play.</p></div><div class="pending-choice-grid">${cards}</div>`;els.pendingMeta.querySelectorAll('[data-pending-index]').forEach((button)=>button.addEventListener('click',()=>lockChoice(Number(button.dataset.pendingIndex))))}
function randomizeRound(){if(state.active?.locked)return;clearTimers();setPendingOptions([]);els.randomizeBtn.disabled=true;els.liveStatus.textContent='Rolling your golfer role…';const options=buildPendingChoices();if(options.length!==3){els.liveStatus.textContent='Could not create three rarity choices.';els.randomizeBtn.disabled=false;return}const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const role=options[0];const messages=[`Role rolled: ${role.archetypeName}.`,`Origin: ${role.gender}, ${role.ageGroup}.`,'Revealing three rarity choices…'];messages.forEach((message,i)=>{const id=setTimeout(()=>{els.liveStatus.textContent=message},reduced?0:i*350);state.revealTimeouts.push(id)});const id=setTimeout(()=>{setPendingOptions(options);els.liveStatus.textContent='Choose the rarity you will role-play.';els.randomizeBtn.disabled=false},reduced?0:1100);state.revealTimeouts.push(id)}
function lockChoice(index){const p=state.pendingOptions[index];if(!p||state.active?.locked)return;state.progressVisible=false;state.active={profileId:p.id,gender:p.gender,ageGroup:p.ageGroup,rarity:p.rarity,archetypeName:p.archetypeName,performanceLabel:p.performanceLabel,clubs:{...p.clubs},teeYardage:p.teeYardage,distanceModelVersion:p.distanceModelVersion,coinResult:p.coinResult,dieRoll:p.dieRoll,startingHoleNumber:1,currentHoleNumber:1,startingHoleConfirmed:false,penaltyStrokesByHole:{},shotResults:[],chipResults:[],puttingResults:[],locked:true,startedAt:new Date().toISOString()};saveRound();state.pendingRole=null;setPendingOptions([]);renderState();els.liveStatus.textContent=`Role locked: ${p.rarity} ${p.archetypeName}.`}
function normalizeHole(value){const n=Number(value);return Number.isInteger(n)&&n>=1&&n<=18?n:1}
function buildHoleSequence(start){return Array.from({length:18},(_,i)=>((normalizeHole(start)-1+i)%18)+1)}
function completedHoleSet(){return new Set((state.active?.puttingResults||[]).map((r)=>r.holeNumber))}
function getCurrentHole(){const n=Number(state.active?.currentHoleNumber);return Number.isInteger(n)&&n>=1&&n<=18?n:inferCurrentHole()}
function inferCurrentHole(){const sequence=buildHoleSequence(state.active?.startingHoleNumber||1);const completed=completedHoleSet();return sequence.find((h)=>!completed.has(h))||sequence[0]}
function hasScoring(){return Boolean((state.active?.shotResults?.length||0)+(state.active?.chipResults?.length||0)+(state.active?.puttingResults?.length||0)+Object.values(state.active?.penaltyStrokesByHole||{}).reduce((s,v)=>s+(Number(v)||0),0))}
function nextShotNumber(hole){return(state.active?.shotResults||[]).filter((r)=>r.holeNumber===hole).length+(state.active?.chipResults||[]).filter((r)=>r.holeNumber===hole).length+1}
function penaltyFor(hole){return Number(state.active?.penaltyStrokesByHole?.[hole])||0}
function setPenalty(hole,value){state.active.penaltyStrokesByHole[hole]=Math.max(0,Math.min(20,Math.round(Number(value)||0)));saveRound();renderCurrentHole();renderRoundScore()}
function summarizeHole(hole){const shots=(state.active?.shotResults||[]).filter((r)=>r.holeNumber===hole);const chips=(state.active?.chipResults||[]).filter((r)=>r.holeNumber===hole);const putting=(state.active?.puttingResults||[]).find((r)=>r.holeNumber===hole)||null;const putts=putting?putting.puttsTaken:0;const penalties=penaltyFor(hole);const distanceReduction=shots.reduce((s,r)=>s+(r.strokeCredits||0),0)/100;const chipReduction=chips.reduce((s,r)=>s+(r.strokeCredits||0),0)/100;const gross=shots.length+chips.length+putts+penalties;return{holeNumber:hole,fullShotCount:shots.length,chipShotCount:chips.length,puttsTaken:putts,penaltyStrokes:penalties,grossScore:gross,distanceReduction,chipReduction,adjustedBeforePuttingBonus:gross-distanceReduction-chipReduction,isComplete:Boolean(putting)}}
function summarizePutting(){const results=state.active?.puttingResults||[];const holesRecorded=new Set(results.map((r)=>r.holeNumber)).size;const totalPutts=results.reduce((s,r)=>s+r.puttsTaken,0);const average=holesRecorded?totalPutts/holesRecorded:0;const rule=PUTTING_RULES[state.active?.rarity]||PUTTING_RULES.Common;const meets=holesRecorded>0&&average<=rule.maximumAveragePuttsPerHole;const maximumBonus=rule.fullBonus*(holesRecorded/18);return{holesRecorded,totalPutts,average,rule,meets,maximumBonus,currentBonus:meets?maximumBonus:0}}
function summarizeRound(){const holes=Array.from({length:18},(_,i)=>summarizeHole(i+1));const putting=summarizePutting();const gross=holes.reduce((s,h)=>s+h.grossScore,0);const distanceReduction=holes.reduce((s,h)=>s+h.distanceReduction,0);const chipReduction=holes.reduce((s,h)=>s+h.chipReduction,0);return{holes,holesCompleted:holes.filter((h)=>h.isComplete).length,gross,distanceReduction,chipReduction,putting,final:gross-distanceReduction-chipReduction-putting.currentBonus}}
function nextIncompleteAfter(hole){const sequence=buildHoleSequence(state.active.startingHoleNumber);const completed=completedHoleSet();const idx=sequence.indexOf(hole);for(let i=1;i<=18;i+=1){const candidate=sequence[(idx+i)%18];if(!completed.has(candidate))return candidate}return null}
function navigateHole(direction){const sequence=buildHoleSequence(state.active.startingHoleNumber);const idx=sequence.indexOf(getCurrentHole());state.active.currentHoleNumber=sequence[(idx+direction+18)%18];saveRound();resetShotMode(false);renderState();els.liveStatus.textContent=`Now viewing Hole ${state.active.currentHoleNumber}.`}
