function renderCurrentHole(){
  if(!state.active?.locked){els.currentHoleOut.innerHTML='';return}
  const current=getCurrentHole();state.active.currentHoleNumber=current;const summary=summarizeHole(current);const played=completedHoleSet().size;const start=normalizeHole(state.active.startingHoleNumber||1);const started=hasScoring()||state.active.startingHoleConfirmed;
  const startOptions=Array.from({length:18},(_,i)=>`<option value="${i+1}" ${i+1===start?'selected':''}>Hole ${i+1}</option>`).join('');
  const jumpOptions=buildHoleSequence(start).map((h)=>`<option value="${h}" ${h===current?'selected':''}>Hole ${h}</option>`).join('');
  els.currentHoleOut.innerHTML=`<div id="currentHolePanel" tabindex="-1"><div class="hole-navigator"><button id="previousHoleBtn" class="hole-arrow-btn" type="button" aria-label="Go to previous hole">‹</button><div class="hole-navigator-center"><div class="current-hole-label">HOLE ${current}</div><div class="holes-played-label">${played} ${played===1?'hole played':'holes played'}</div></div><button id="nextHoleBtn" class="hole-arrow-btn" type="button" aria-label="Go to next hole">›</button></div>${started?'':`<div class="confirm-card"><div class="score-label">STARTING HOLE</div><select id="startingHoleSelect">${startOptions}</select><button id="startRoundBtn" type="button">Start Round</button></div>`}<details class="secondary-details"><summary>Hole Details</summary><div class="mt8 score-note">Starting Hole: ${start}</div><div class="score-note">Status: ${summary.isComplete?'Complete':'In Progress'}</div><div class="score-note">Full Shots: ${summary.fullShotCount}</div><div class="score-note">Chips: ${summary.chipShotCount}</div><div class="score-note">Putts: ${summary.isComplete?summary.puttsTaken:'Not Recorded'}</div><div class="score-note">Penalties: ${summary.penaltyStrokes}</div><div class="score-note"><strong>${summary.isComplete?'Hole Score':'Strokes Recorded'}: ${summary.isComplete?summary.grossScore:summary.fullShotCount+summary.chipShotCount+summary.penaltyStrokes}</strong></div><div class="mt8"><label for="currentHoleSelect">Jump to Hole</label><select id="currentHoleSelect">${jumpOptions}</select></div><div class="score-label mt8">Penalty Strokes</div><div class="penalty-controls"><button id="penaltyDownBtn" class="btn-secondary" type="button">−</button><span class="penalty-value">${summary.penaltyStrokes}</span><button id="penaltyUpBtn" class="btn-secondary" type="button">+</button></div></details></div>`;
  $('previousHoleBtn').addEventListener('click',()=>navigateHole(-1));$('nextHoleBtn').addEventListener('click',()=>navigateHole(1));
  $('startRoundBtn')?.addEventListener('click',()=>{const selected=normalizeHole($('startingHoleSelect').value);state.active.startingHoleNumber=selected;state.active.currentHoleNumber=selected;state.active.startingHoleConfirmed=true;saveRound();renderCurrentHole();renderRoundScore();els.liveStatus.textContent=`Round starts on Hole ${selected}.`});
  $('currentHoleSelect').addEventListener('change',(e)=>{state.active.currentHoleNumber=normalizeHole(e.target.value);saveRound();resetShotMode(false);renderState();els.liveStatus.textContent=`Now viewing Hole ${state.active.currentHoleNumber}.`});
  $('penaltyDownBtn').addEventListener('click',()=>setPenalty(current,summary.penaltyStrokes-1));$('penaltyUpBtn').addEventListener('click',()=>setPenalty(current,summary.penaltyStrokes+1));
}
function renderRoundScore(){
  if(!state.active?.locked||!hasScoring()){els.progressToggleWrap.innerHTML='';els.roundScore.innerHTML='';return}
  els.progressToggleWrap.innerHTML=`<button id="progressToggleBtn" type="button" class="btn-inline btn-secondary">${state.progressVisible?'Hide Current Progress':'Show Current Progress'}</button>`;$('progressToggleBtn').addEventListener('click',()=>{state.progressVisible=!state.progressVisible;renderRoundScore()});
  if(!state.progressVisible){els.roundScore.innerHTML='';return}
  const round=summarizeRound();const current=getCurrentHole();const byHole=new Map(round.holes.map((h)=>[h.holeNumber,h]));
  const scorecard=buildHoleSequence(state.active.startingHoleNumber).map((number)=>{const h=byHole.get(number);const cls=`hole-score-card ${h.isComplete?'completed-hole':''} ${number===current?'current-hole':''}`;return`<details class="${cls}"><summary>Hole ${number} — ${h.isComplete?`${h.grossScore} strokes`:'In Progress'}</summary><div class="score-note mt8">Full shots: ${h.fullShotCount}</div><div class="score-note">Chips: ${h.chipShotCount}</div><div class="score-note">Putts: ${h.isComplete?h.puttsTaken:'Not Recorded'}</div><div class="score-note">Penalties: ${h.penaltyStrokes}</div><div class="score-note">Distance reward: −${format(h.distanceReduction)}</div><div class="score-note">Short-game reward: −${format(h.chipReduction)}</div><div class="score-note">Adjusted before putting bonus: ${format(h.adjustedBeforePuttingBonus)}</div></details>`}).join('');
  const heading=round.holesCompleted===18?'ROUND COMPLETE':'CURRENT ROLL PLAY SCORE';
  const histories=[['Distance Quest History',(state.active.shotResults||[]).slice().reverse().map((r)=>`<div class="shot-history-item">Hole ${r.holeNumber}, Shot ${r.shotNumber}: ${escapeHtml(r.assignedClub)} at ${r.requiredDistanceYards} yd — ${r.hitDistanceWindow?'Quest complete':'Quest missed'} — ${format(r.strokeReward)} strokes</div>`).join('')||'<div class="shot-history-item">No distance quests recorded.</div>'],['Short-Game Quest History',(state.active.chipResults||[]).slice().reverse().map((r)=>`<div class="shot-history-item">Hole ${r.holeNumber}, Shot ${r.shotNumber}: ${escapeHtml(r.recommendedClub)} — ${r.hitChipTarget?'Quest complete':'Quest missed'} — ${format(r.strokeReward)} strokes</div>`).join('')||'<div class="shot-history-item">No short-game quests recorded.</div>'],['Putting History',(state.active.puttingResults||[]).slice().reverse().map((r)=>`<div class="shot-history-item">Hole ${r.holeNumber}: ${r.puttsTaken===0?'Hole out':`${r.puttsTaken} putts`}</div>`).join('')||'<div class="shot-history-item">No putting recorded.</div>']].map(([title,items])=>`<div class="score-label mt10">${title}</div><div class="shot-history">${items}</div>`).join('');
  els.roundScore.innerHTML=`<div class="score-panel"><div class="score-label">SCORECARD</div><div class="scorecard-list">${scorecard}</div></div><div class="score-panel mt10"><div class="score-label">${heading}</div><div class="score-note">Holes Completed: ${round.holesCompleted} of 18</div><div class="score-note">Gross Strokes: ${format(round.gross)}</div><div class="score-note">Distance Quest Rewards: −${format(round.distanceReduction)}</div><div class="score-note">Short-Game Quest Rewards: −${format(round.chipReduction)}</div><div class="score-note">Current Putting Quest Bonus: −${format(round.putting.currentBonus)}</div><div class="score-stat">${round.holesCompleted===18?'Final':'Current'} Roll Play Score: ${format(round.final)}</div></div><div class="score-panel mt10"><div class="score-label">PUTTING QUEST</div><div class="score-note">Holes Completed: ${round.putting.holesRecorded}</div><div class="score-note">Total Putts: ${round.putting.totalPutts}</div><div class="score-note">Average: ${format(round.putting.average)} per hole</div><div class="score-note">${state.active.rarity} target: ${format(round.putting.rule.maximumAveragePuttsPerHole)} or fewer</div><div class="score-note">Current Bonus: ${format(round.putting.currentBonus)}</div><div class="score-note">${round.putting.meets?'Quest on target':'Outside the putting quest target'}</div>${round.putting.meets?'':`<details class="secondary-details"><summary>Bonus detail</summary><div class="score-note mt8">Maximum bonus available so far: ${format(round.putting.maximumBonus)}</div></details>`}</div><details class="secondary-details mt10"><summary>Quest History</summary>${histories}</details>`;
}
function renderCharacterCardSvg(profile){
  const accent={Common:'#8A94A6',Rare:'#4EA1FF',Epic:'#B56CFF',Legendary:'#F2C94C'}[profile.rarity]||'#F2C94C';
  const rows=CLUBS.map((club,index)=>{const y=570+index*31;const fill=index%2===0?'#131A25':'#1A2230';return`<rect x="26" y="${y}" width="368" height="28" rx="8" fill="${fill}"/><text x="40" y="${y+19}" class="club">${escapeHtml(club)}</text><text x="378" y="${y+19}" text-anchor="end" class="val">${profile.clubs[club]} yd</text>`}).join('');
  const windowPct=Math.round(DISTANCE_RULES[profile.rarity].halfWindowRate*100);const reward=format(DISTANCE_RULES[profile.rarity].reward);
  return`<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 420 1100" role="img" aria-labelledby="title desc"><title id="title">Roll Play Golf ${escapeHtml(profile.rarity)} ${escapeHtml(profile.archetypeName)} character card</title><desc id="desc">Modeled total-distance club targets for a ${escapeHtml(profile.gender)} ${escapeHtml(profile.ageGroup)} ${escapeHtml(profile.rarity)} golfer character.</desc><rect x="8" y="8" width="404" height="1084" rx="24" fill="#0B111A" stroke="${accent}" stroke-width="3"/><text x="210" y="58" text-anchor="middle" class="brand">ROLL PLAY GOLF</text><text x="210" y="84" text-anchor="middle" class="sub">A GOLF RPG</text><rect x="24" y="108" width="372" height="170" rx="14" fill="#141D2A" stroke="#2A3445"/><text x="40" y="140" class="head">${escapeHtml(profile.archetypeName).toUpperCase()}</text><text x="40" y="168" class="meta">${profile.gender} • ${escapeHtml(profile.ageGroup)}</text><text x="40" y="198" class="rarity">${profile.rarity.toUpperCase()} — ${escapeHtml(profile.performanceLabel)}</text><text x="40" y="228" class="meta">Tee Quest: ${profile.teeYardage.toLocaleString()} yards</text><text x="40" y="256" class="metaSmall">Role locked for this round</text><rect x="24" y="298" width="372" height="132" rx="14" fill="#141D2A" stroke="#2A3445"/><text x="40" y="328" class="head">DISTANCE QUEST</text><text x="40" y="358" class="metaSmall">Finish within ±${windowPct}% of the selected target</text><text x="40" y="386" class="metaSmall">Reward: ${reward} stroke${Number(reward)===1?'':'s'} per success</text><text x="40" y="414" class="metaSmall">All values are modeled total distance</text><text x="28" y="548" class="head">CLUB TARGETS</text>${rows}<text x="210" y="1064" text-anchor="middle" class="note">Driver off the deck or next-closest club allowed • Putter allowed on green</text><style>.brand{fill:#F4F7FB;font:800 25px system-ui,sans-serif}.sub{fill:#AAB3C2;font:700 14px system-ui,sans-serif}.rarity,.head{fill:${accent};font:800 15px system-ui,sans-serif}.meta{fill:#E7ECF7;font:600 15px system-ui,sans-serif}.metaSmall{fill:#D7DFED;font:600 13px system-ui,sans-serif}.club{fill:#E7ECF7;font:600 14px system-ui,sans-serif}.val{fill:#F4F7FB;font:700 14px system-ui,sans-serif}.note{fill:#AAB3C2;font:600 11px system-ui,sans-serif}</style></svg>`;
}
function characterCardDataUrl(profile){return`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(renderCharacterCardSvg(profile))}`}
function renderPrintCards(){els.printGrid.innerHTML=state.profiles.map((p)=>`<article class="print-card"><img src="${characterCardDataUrl(p)}" alt="Roll Play Golf ${escapeHtml(p.rarity)} ${escapeHtml(p.archetypeName)} character card"></article>`).join('')}
function renderState(){const profile=activeProfile();const hasActive=Boolean(profile&&state.active?.locked);els.randomizeBtn.classList.toggle('hidden',hasActive);els.resumeBtn.classList.toggle('hidden',!hasActive);els.resetBtn.classList.toggle('hidden',!hasActive);els.activeSection.classList.toggle('hidden',!hasActive);els.playSection.classList.toggle('hidden',!hasActive);if(!hasActive){els.activeMeta.innerHTML='';els.currentHoleOut.innerHTML='';els.distanceGrid.innerHTML='';els.playOut.innerHTML='';els.shotConfirmOut.innerHTML='';els.roundScore.innerHTML='';els.progressToggleWrap.innerHTML='';return}els.activeMeta.innerHTML=`<div class="meta-block"><div class="badge-row"><span class="badge">Roll Play Golf</span><span class="badge">${escapeHtml(profile.archetypeName)}</span><span class="badge ${profile.gender==='Female'?'badge-female':'badge-male'}">${profile.gender}</span><span class="badge">${escapeHtml(profile.ageGroup)}</span><span class="badge">${profile.rarity}</span><span class="badge">${escapeHtml(profile.performanceLabel)}</span></div><p class="locked">ROLE LOCKED</p><p class="muted">You are role-playing this golfer for the current round.</p></div>`;els.teeYardage.textContent=profile.teeYardage;const cardUrl=characterCardDataUrl(profile);els.activeCard.src=cardUrl;els.activeCard.alt=`Roll Play Golf ${profile.rarity} ${profile.archetypeName} character card`;els.activeCard.onclick=()=>openZoom(cardUrl,els.activeCard.alt);renderCurrentHole();renderDistanceButtons();renderRoundScore();updateInstructionVisibility()}
function renderDistanceButtons(){const profile=activeProfile();if(!profile)return;els.distanceGrid.classList.remove('hidden');els.distanceGrid.innerHTML='';CLUBS.forEach((club)=>{const button=document.createElement('button');button.type='button';button.className='distance-btn';button.textContent=`${profile.clubs[club]} yd — ${club}`;button.addEventListener('click',()=>selectDistance(club,profile.clubs[club]));els.distanceGrid.appendChild(button)});const around=document.createElement('button');around.type='button';around.className='around-green-btn';around.textContent='Around the Green';around.addEventListener('click',openAroundGreen);els.distanceGrid.appendChild(around)}
function findDriverSubstitute(target,clubs){let best=null;for(const club of DRIVER_SUBSTITUTES){const diff=Math.abs(target-clubs[club]);if(!best||diff<best.diff)best={club,diff}}return best}
function selectDistance(club,distance){const rule=DISTANCE_RULES[state.active.rarity];const hole=getCurrentHole();const allowed=distance*rule.halfWindowRate;state.currentShot={holeNumber:hole,shotNumber:nextShotNumber(hole),assignedClub:club,requiredDistanceYards:distance,minimumDistanceYards:distance-allowed,maximumDistanceYards:distance+allowed,strokeReward:rule.reward,strokeCredits:rule.reward*100,rarity:state.active.rarity};state.currentPutting=null;state.currentAroundGreen=null;state.currentChipRecommendation=null;els.distanceGrid.classList.add('hidden');const substitute=club==='Driver'?findDriverSubstitute(distance,activeProfile().clubs):null;els.playOut.innerHTML=`<div class="target-window-card"><h3>${club}</h3><p>Target: ${distance} yd</p><p>Target Zone: ${Math.round(distance-allowed)}–${Math.round(distance+allowed)} yd</p><p>Reward: ${format(rule.reward)} strokes</p>${substitute?`<details class="secondary-details"><summary>Driver Option</summary><p>Use Driver off the deck or ${substitute.club}. The target does not change.</p></details>`:''}<div class="result-buttons"><button id="hitTargetBtn" type="button">Complete Distance Quest</button><button id="missTargetBtn" type="button" class="btn-secondary">Miss Distance Quest</button></div><details class="secondary-details"><summary>Optional details</summary><label for="shotNote">Note</label><input id="shotNote" maxlength="120" placeholder="Add a note"></details></div>`;$('hitTargetBtn').addEventListener('click',()=>recordShot(true));$('missTargetBtn').addEventListener('click',()=>recordShot(false));els.playResetBtn.classList.remove('hidden');focusPlay()}
function recordShot(hit){const shot=state.currentShot;if(!shot)return;const result={...shot,id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,hitDistanceWindow:hit,strokeReward:hit?shot.strokeReward:0,strokeCredits:hit?shot.strokeCredits:0,note:$('shotNote')?.value.trim()||'',recordedAt:new Date().toISOString()};state.active.shotResults.push(result);saveRound();renderCurrentHole();renderRoundScore();els.shotConfirmOut.innerHTML=`<div class="confirm-card"><div class="confirm-title">${hit?'Distance Quest Complete':'Distance Quest Missed'}</div><div class="confirm-subtitle">${hit?`${format(shot.strokeReward)} strokes earned`:'No reward earned'}</div><div class="confirm-actions"><button id="nextShotBtn" class="btn-secondary">Next Shot</button><button id="undoShotBtn" class="btn-secondary">Undo</button></div></div>`;$('nextShotBtn').addEventListener('click',()=>{els.shotConfirmOut.innerHTML=''});$('undoShotBtn').addEventListener('click',()=>undoShot(result.id));resetShotMode(false);focusPlay()}
function undoShot(id){const last=state.active.shotResults.at(-1);if(!last||last.id!==id){els.liveStatus.textContent='Only the most recent distance quest can be undone.';return}state.active.shotResults.pop();saveRound();renderCurrentHole();renderRoundScore();els.shotConfirmOut.innerHTML='';els.liveStatus.textContent='Last distance quest removed.'}
